### ISSUE TITLE
大佬，https://kernelgo.org 失效了

### ISSUE THREAD

**Issue by Martins3** [fangying/fangying.github.io#4]

**Comment by meehoyuen** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fangying** [comment]
新的地址是：https://blog.kernel.love

hahahaha ***@***.***> 于2024年5月30日周四 10:31写道：

**Comment by meehoyuen** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Martins3** [comment]
![image](https://github.com/fangying/fangying.github.io/assets/16731244/4db02178-e7dc-47a3-9d73-8740eb959260)

**Comment by fangying** [comment]
@Martins3 新的网站地址 https://blog.kernel.love
